name: PrimeroJob
on: 
  push:
    branches: ["QA"]
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Usando a Branch de QA
